/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as BookingRouteImport } from "./routes/booking";
import { Route as AdminRouteImport } from "./routes/admin";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as AdminIndexRouteImport } from "./routes/admin.index";
import { Route as AdminEmployeesRouteImport } from "./routes/admin.employees";
import { Route as AdminBookingsRouteImport } from "./routes/admin.bookings";

const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
});
const BookingRoute = BookingRouteImport.update({
  id: "/booking",
  path: "/booking",
  getParentRoute: () => rootRouteImport,
});
const AdminRoute = AdminRouteImport.update({
  id: "/admin",
  path: "/admin",
  getParentRoute: () => rootRouteImport,
});
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
});
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AdminRoute,
});
const AdminEmployeesRoute = AdminEmployeesRouteImport.update({
  id: "/employees",
  path: "/employees",
  getParentRoute: () => AdminRoute,
});
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: "/bookings",
  path: "/bookings",
  getParentRoute: () => AdminRoute,
});

const AdminRouteChildren = {
  AdminBookingsRoute: AdminBookingsRoute,
  AdminEmployeesRoute: AdminEmployeesRoute,
  AdminIndexRoute: AdminIndexRoute,
};

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren);

const rootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BookingRoute: BookingRoute,
  LoginRoute: LoginRoute,
};
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes();
