/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as DriverRouteImport } from './routes/Driver'
import { Route as CustomerRouteImport } from './routes/Customer'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminAdminDashboardRouteImport } from './routes/admin/adminDashboard'
import { Route as AdminAdminRouteImport } from './routes/admin/admin'
import { Route as AdminAdminEmployeesRouteImport } from './routes/admin/admin.employees'
import { Route as AdminAdminBookingRouteImport } from './routes/admin/admin.booking'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRoute = DriverRouteImport.update({
  id: '/Driver',
  path: '/Driver',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRoute = CustomerRouteImport.update({
  id: '/Customer',
  path: '/Customer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminDashboardRoute = AdminAdminDashboardRouteImport.update({
  id: '/admin/adminDashboard',
  path: '/admin/adminDashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/admin/admin',
  path: '/admin/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminEmployeesRoute = AdminAdminEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminBookingRoute = AdminAdminBookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => AdminAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Customer': typeof CustomerRoute
  '/Driver': typeof DriverRoute
  '/booking': typeof BookingRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/admin/admin': typeof AdminAdminRouteWithChildren
  '/admin/adminDashboard': typeof AdminAdminDashboardRoute
  '/admin/admin/booking': typeof AdminAdminBookingRoute
  '/admin/admin/employees': typeof AdminAdminEmployeesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Customer': typeof CustomerRoute
  '/Driver': typeof DriverRoute
  '/booking': typeof BookingRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/admin/admin': typeof AdminAdminRouteWithChildren
  '/admin/adminDashboard': typeof AdminAdminDashboardRoute
  '/admin/admin/booking': typeof AdminAdminBookingRoute
  '/admin/admin/employees': typeof AdminAdminEmployeesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Customer': typeof CustomerRoute
  '/Driver': typeof DriverRoute
  '/booking': typeof BookingRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/admin/admin': typeof AdminAdminRouteWithChildren
  '/admin/adminDashboard': typeof AdminAdminDashboardRoute
  '/admin/admin/booking': typeof AdminAdminBookingRoute
  '/admin/admin/employees': typeof AdminAdminEmployeesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Customer'
    | '/Driver'
    | '/booking'
    | '/login'
    | '/profile'
    | '/admin/admin'
    | '/admin/adminDashboard'
    | '/admin/admin/booking'
    | '/admin/admin/employees'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Customer'
    | '/Driver'
    | '/booking'
    | '/login'
    | '/profile'
    | '/admin/admin'
    | '/admin/adminDashboard'
    | '/admin/admin/booking'
    | '/admin/admin/employees'
  id:
    | '__root__'
    | '/'
    | '/Customer'
    | '/Driver'
    | '/booking'
    | '/login'
    | '/profile'
    | '/admin/admin'
    | '/admin/adminDashboard'
    | '/admin/admin/booking'
    | '/admin/admin/employees'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomerRoute: typeof CustomerRoute
  DriverRoute: typeof DriverRoute
  BookingRoute: typeof BookingRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  AdminAdminRoute: typeof AdminAdminRouteWithChildren
  AdminAdminDashboardRoute: typeof AdminAdminDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Driver': {
      id: '/Driver'
      path: '/Driver'
      fullPath: '/Driver'
      preLoaderRoute: typeof DriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Customer': {
      id: '/Customer'
      path: '/Customer'
      fullPath: '/Customer'
      preLoaderRoute: typeof CustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/adminDashboard': {
      id: '/admin/adminDashboard'
      path: '/admin/adminDashboard'
      fullPath: '/admin/adminDashboard'
      preLoaderRoute: typeof AdminAdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/admin': {
      id: '/admin/admin'
      path: '/admin/admin'
      fullPath: '/admin/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/admin/employees': {
      id: '/admin/admin/employees'
      path: '/employees'
      fullPath: '/admin/admin/employees'
      preLoaderRoute: typeof AdminAdminEmployeesRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/admin/booking': {
      id: '/admin/admin/booking'
      path: '/booking'
      fullPath: '/admin/admin/booking'
      preLoaderRoute: typeof AdminAdminBookingRouteImport
      parentRoute: typeof AdminAdminRoute
    }
  }
}

interface AdminAdminRouteChildren {
  AdminAdminBookingRoute: typeof AdminAdminBookingRoute
  AdminAdminEmployeesRoute: typeof AdminAdminEmployeesRoute
}

const AdminAdminRouteChildren: AdminAdminRouteChildren = {
  AdminAdminBookingRoute: AdminAdminBookingRoute,
  AdminAdminEmployeesRoute: AdminAdminEmployeesRoute,
}

const AdminAdminRouteWithChildren = AdminAdminRoute._addFileChildren(
  AdminAdminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomerRoute: CustomerRoute,
  DriverRoute: DriverRoute,
  BookingRoute: BookingRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  AdminAdminRoute: AdminAdminRouteWithChildren,
  AdminAdminDashboardRoute: AdminAdminDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.jsx'
import type { startInstance } from './start.js'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
